import clsx from "clsx";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

const esko = localFont({
  src: "../../public/fonts/esko.ttf",
  display: "swap",
  variable: "--font-esko",
});

const gridular = localFont({
  src: "../../public/fonts/gridular.otf",
  display: "swap",
  variable: "--font-gridular",
});

const water = localFont({
  src: "../../public/fonts/water.otf",
  display: "swap",
  variable: "--font-water",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, esko.variable, gridular.variable, water.variable)}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
